Develop
MeFormei/web pull request #9
Opened 2017-05-05 18:06 UTC by joabfg

adicionando um tela

2017-05-05 23:29 UTC, 7robertodantas requested changes

2017-05-05 23:29 UTC, 7robertodantas commented on script/meformei.js
> +	if (flag == true)
Não necessita fazer a comparação com true. Ajustar para **if(flag)**.

2017-05-05 23:29 UTC, 7robertodantas commented on script/meformei.js
> +		$(".feedback-movement").fadeOut(300);
o elemento $(".feedback-movement") é utilizada tanto no if quanto no else. Nesse caso, por questões de otimização e boa prática, sugere-se armazenar a referência em uma variável.

```javascript
var $feedbackMovement = $(".feedback-movement");
if(flag) {
 $feedbackMovement.fadeOut(300);
} else {
 $feedbackMovement.fadeIn(300);
}
```

2017-05-05 23:29 UTC, 7robertodantas commented on script/meformei.js
> +function onCoordinates(coordX, coordY) {
A função deverá funcionar como um registro de callback (subscribe). Isto é, aqui não deveria saber da lógica para desenhar o círculo. Mas sim, apenas saber qual função deverá chamar quando ocorrer o tópico de coordenada, similar ao que acontece nas funções onLeft, onRight, onTop e onDown.

```javascript
function onCoordinate(callback) {
callbacks[TOPIC_COORDINATE] = callback;
}
```

A implementação dessa função de desenho deve ser implementada na página principal, e não aqui.

2017-05-05 23:29 UTC, 7robertodantas commented on script/meformei.js
> +function drawCircle(relativeX, relativeY) {
Conforme o comentário da função onCoordinates, é preferivel que aqui não tenha detalhes e implementações que são de uma view específica.

Nesse caso, pode-se criar um arquivo .js novo com essas implementações relacionadas ao quadro de noção espacial, ou então, no script da página onde será exibido.

2017-05-05 23:29 UTC, 7robertodantas commented on turma.html
> +<!DOCTYPE html>
Não entendi turma.html, isso seria o local para o formulário de turma? Caso não, as visualizações deverão estar juntas no **index.html**

2017-05-05 23:29 UTC, 7robertodantas commented on script/meformei.js
> +		else if (topicStr === TOPIC_POSITION) {
Ajustar para chamar apenas o callback, não colocar lógica aqui.

A função de callback também pode ter como parâmetro um booleano para definir se há posição ou não, ou pode-se dividir em duas funções que recebem callbacks (onNoCoordinate e onCoordinate)

**Possibilidade 01**
```javascript
callbacks[TOPIC_COORDINATE](payloadStr == 'none'); // chama callback passando parâmetro booleano
```

**Possibilidade 02** (Duas funções separadas, sem parâmetro booleano)
```javascript
if(payloadStr == 'none'){
 callbaks[TOPIC_COORDINATE]();
 }
else {
 callbacks[TOPIC_NO_COORDINATE](); 
}
```

2017-05-05 23:29 UTC, 7robertodantas commented on script/meformei.js
criar topico coordinate e utilizá-lo.
```javascript
const TOPIC_COORDINATE = 'coordinate';
```

2017-05-07 19:48 UTC, joabfg commented on turma.html
> +<!DOCTYPE html>
você é um scrum Master muito casquinha

2017-05-07 19:48 UTC, joabfg commented on turma.html
> +<!DOCTYPE html>
turma.html é uma das 3 telas que teremos nessa sprint.
Irá exibir apenas as informações da turma.

2017-05-07 19:50 UTC, joabfg commented on script/meformei.js
Estas alterações no meFormei.js entraram no meu request pois a equipe fez push na branch develop e não solicitou pull request. gostaria que se possível integrasse os arquivos de view.

2017-05-07 21:58 UTC, 7robertodantas approved these changes
Correções validadas

2017-05-07 21:58 UTC, merged